### ISSUE TITLE
Create a Release Branch

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1002]
## User Story
As a developer I would like a release branch so that I have better control over what goes to production. 

## Impacts
Our git flow

## Assumptions
- Having a "stable" branch is also a requirement for e2e-deploy (https://github.com/RedHatInsights/e2e-deploy/blob/master/docs/pipeline.md#overview)
- Building an automatic release tagging in a Jenkins job would also be great so we can consistently and reproducibly checkout the exact state of specific releases. 
- We could tag everything that passes vortex as a potential release and/or tag actual releases when we do the manual push to production from staging
- All PRs would still go to master

## Acceptance Criteria

- [x] Release branch exists
- [x] Releases get tagged
- [ ] A release also sends release notes (git commit messages) to koku-bots channel
- [x] Appropriate hooks exist to protect branch

**Comment by adberglund** [comment]
The `stable` branch now exists in the koku repo. There is still work to be done for consistent tagging of releases and creating pre-commit hooks.

**Comment by blentz** [comment]
I did some investigation on the subject of commit hooks and branch restrictions.

The kind of git hook that we need to manage the stable branch would be a pre-receive hook. This is a server-side hook, so this feature is only available to Github Enterprise, not the main Github service. Due to the ability to execute arbitrary code inside the hook, it's easy to see why this is not supported.

One alternative approach is to use protected branches to set rules that restrict who can push to the stable branch. This way, we could set a restriction that only (for example) the Jenkins bot can push to stable, then we can create a Jenkins job to perform the checks we require for pushing to the stable branch in lieu of a git hook.

There is some risk involved with delegating our checks to Jenkins. We might want some way to assure that someone doesn't simply create their own job to push to stable without the required checks. But, Jenkins authenticates against the RH SSO, so we at least have user auditing and the ability to track down who pushed to the stable branch in the event of a rogue job being created.
