### ISSUE TITLE
Configuring a Provider (AWS ARN & S3 Bucket)

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#102]
## User Story
As a user, I want to be able to configure an AWS account so that the service can read the AWS Cost & Usage Reports from an S3 bucket within my account and obtain the AWS organization information to control cost visibility.

## Impacts
API, UI, Docs

## Role
User

## Assumptions

- We will provide docs (maybe embedded in the UI) to describe to the user the steps to configure S3 to capture AWS Cost CSV files.
- We will provide docs (maybe embedded in the UI) to describe to the user the steps to add a policy that provides the service access to the S3 bucket and AWS organization.
- The user will provide the ARN which we will verify access to the S3 bucket and AWS organization.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | PATCH | 
 | **Path** | /api/v1/providers/(provider uuid)/ | 
 | **Body** | crn, bucket | 
 | **Response** | uuid, id, name, type (aws), crn, bucket | 

## UI Details
A view exist to configure an AWS account.

## Acceptance Criteria

- [ ] Verify that a user can configure an existing AWS account in their customer and the response provides the account (uuid, id, name, type, crn).
- [ ] Verify that an account cannot be configured if the provided CRN doesn’t allow access to an S3 bucket and AWS organization information.

**Comment by chambridge** [comment]
Looks like this is done in a single POST in the Cloud Health API. Should we just collapse this into https://github.com/project-koku/koku/issues/99?

**Comment by blentz** [comment]
We should probably aim to enable access via Role-based cross-account access - https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

**Comment by adberglund** [comment]
I agree with Brett. For a practical example I can point to how it's being done in cloudigrade. From what I remember seeing in the CloudHealth API from a screen share a week+ ago it looked like they provided two ways. 1) What Brett is suggesting. 2) actually creating a user in the customer account that has required access. Not sure why supporting both is important, but role based is nice because we don't have to keep any credentials. If the role exists, we can use `STS` to "assume role" and AWS handles the auth.

**Comment by chambridge** [comment]
Based on https://github.com/project-koku/koku/issues/102#issuecomment-387482203 I have updated #99 so this can be collapsed into a single API.
