### ISSUE TITLE
Remove unused tags from database

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1057]
@dccurtis commented on [Fri May 10 2019](https://github.com/project-koku/masu/issues/439)

## User Story
As user I do not want to see TAGs in the API that are no longer associated with my account.

## Impacts
Ex. API

## Implementation Details
- Need to remove tags from our AWS, Azure, and OCP tag summary tables when there is no longer a reference to report_period_id (OCP) or bill_id (AWS, Azure)
- Require model changes to add in these columns to those tables 
- Modify the expired data remover to remove tags from removed bills/report_periods. 

## Acceptance Criteria

- [ ] Removing a provider should also remove tags.  Verify with the tags API endpoint and ensure queries by tags works as expected.
- [ ] Running the expired data remover removes the data for the removed date range. 

---

@blentz commented on [Thu May 23 2019](https://github.com/project-koku/masu/issues/439#issuecomment-495274471)

[Bug Triage]

This will probably require schema changes that establish a relationship between the Tags table and the Provider table so that we know which tags are linked to which provider(s).

---

@dccurtis commented on [Fri May 31 2019](https://github.com/project-koku/masu/issues/439#issuecomment-497776154)

Just verified that the tags endpoint is in fact cleared when removing providers. I must have had a bad local setup when I initially opened this.  The issue still remains however that the summary tables are not being updated.

**Comment by dccurtis** [comment]
Also applies to Azure tags

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:
Andrew: "This is an older issue but I pulled it back to New Issues because I want to re-work it slightly in context of tagging requirements for current milestone, there's plenty to do on Tagging but this is a good step along the way. For some backstory, we have this tag summary table a list of tags we've seen for a source and all values for that tag, it has every other reporting database table we have has some way of tying back to a particular source and that time period of a month or a bill, this table does not associate to a particular source nor a time period, so the possibility that this data gets stale is high, you could have a tag that you stopped using 6 months ago and we didn't know to clean up, we might return it as a valid tag thats not actually valid. I think we need to remove tags from our summary tables. A period_id is the openshift equivalent of a bill_id. If we add these two columns in, what that does is it ties the entry in the table to particular source during a particular time period. We need a model change to do that and probably, we'll need to modify the expired data remover, so there's 2 parts, 1 is updating models, 2nd part is making sure expired data remover actually cleans out the data. There's a side benefit [to completing this story], if tags get associated with sources, we can use this table for tag association when doing openshift on infrastructure, right now it's a costly operation but this table would allow us to do a quick tag match here.

**Comment by lcouzens** [comment]
Verfied
