### ISSUE TITLE
Unit Test SQL

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1058]
## User Story
As a developer I want our reporting SQL to have unit tests so I can be confident when changing or adding to the processing logic. 

## Notes
Over the summer our intern did some unit test work for our SQL. These tests should be reviewed, hardened, and added to our regular testing to prevent further regressions in our SQL. 

The spirit of this issue is that our reporting SQL blocks are currently a "big miss" in our automated unit tests. The QE integration tests catch a lot of stuff, but we should catch regressions much sooner.

## Assumptions
- Small static data sets or test data generators can be used 
- We calculate in Python the values we expect from the SQL
- Run the SQL and match against Python calculations
- Nobody currently remembers where/how these tests exist but aren't being run… poke @adberglund if you want some ideas of where to look. Maybe it was in the old `masu` repo? Maybe in a dead/abandoned branch?
- Link to tests: https://github.com/project-koku/masu/compare/master...aagarw10:master
- We will put in a good-faith effort to preserve working tests, but the intent here is not to ensure everything that was written months ago still works. Some areas of the code may have diverged, and some tests may no longer be correct or relevant. Let's put a soft cap on this effort at "a few days".
- Furthermore, we intend to attempt grafting the existing tests into koku and lightly adjusting them if possible to fit. The intent here is **not** to extend it to exhaustively test our SQL.
- We have found several existing issues that look related. If we find that the tests we recover sufficiently resolve these issues, we will close them as we go:
  - https://github.com/project-koku/koku/issues/1059
  - https://github.com/project-koku/koku/issues/1060
  - https://github.com/project-koku/koku/issues/1061

## Acceptance Criteria

- [ ] Old tests have been discovered and are running with the normal `tox` test jobs **if** this can be done with moderately low effort. Else, we close this issue effectively as "won't fix".
- [ ] related issues above have been closed or commented-on if the new tests cover them
- [ ] We have a conversation with the team about our findings/successes/failures to graft and to discuss next steps. Is this pattern worth extending? Should we extend for more SQL tests (not in this issue but in the future)? Does anyone know good testing patterns in general for large SQL-ish things like this?

**Comment by infinitewarp** [comment]
I copied the aforementioned changes from masu into koku and spent some time fixing syntax errors that largely resulted from the diverged code base. This now exists in branch [`1058-masu-tests-do-not-merge`](https://github.com/project-koku/koku/commits/1058-masu-tests-do-not-merge). As that name probably indicates, I advise _against_ merging these changes (the tests aren't currently passing anyway) because I do not believe the method in which those tests were originally implemented follows a good pattern that we should embrace and extend.

The pattern used by the copied tests effectively _reimplements_ the calculations from the core masu code and then assert that the _test's calculated values_ match the stored values from the backing service's calculations. This is a brittle method of testing because it duplicates logic, effectively introducing even more code that _itself_ should be tested on a finer-grain level for correctness.

Instead of this approach, I would generally recommend producing and storing with the test code some kind of known-good input fixture data. This could originate from real customer data, or it could originate from a carefully crafted `nise` command. The fixture data could be imported and processed at testing time like normal AWS/OCP/etc. data, and then the saved results could be compared directly to _static known-good_ expected result values. The act of testing here should be a simple act of "load+process, query, and assert equal". The tests should assert _known_ values in the calculated results, not recalculate all of them from scratch.

**Comment by infinitewarp** [comment]
Closing since there's been no additional feedback since I shared that comment in Slack several days ago.
