### ISSUE TITLE
Add support for "GCP-local" providers to nise

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1106]
## User Story
As a koku developer, I want nise to generate local filesystem data for my `GCP-local`-type provider.

## Assumptions
- This should generate data in a format matching GCP's exported billing data files.
- This should be implemented in a pattern matching the behavior for generating local AWS and Azure files.

## Acceptance Criteria

- [ ] nise accepts arguments for generating GCP data
- [ ] nise successfully generates files in the specified path that fit GCP's billing data file format

**Comment by lcouzens** [comment]
So there is a few pieces missing from this. We have the ability to generate data based from static report yamls on the other providers, we need to replicate this on GCP.

The other thing I notice is the path we are generating files in is not were you expect it to be. It seems to create a dir structure based on your current location.

nise --gcp --start-date 2019-10-10 --gcp-report-prefix gcp_nise --gcp-bucket-name ~/gcp_local/

Copied /home/lcouzens/Workspace/nise/gcp_nise-2019-10-18.csv to local directory /home/lcouzens/gcp_local/.

running this command I expect my csv files to be in ~/gcp_local but they end up in a new try structure under that.  ~/gcp_local/home/lcouzens/Workspace/nise/gcp_nise-2019-10-18.csv

My guess is its copying the tree structure with the csv instead of just the csv.

**Comment by lcouzens** [comment]
Verified!
