### ISSUE TITLE
Write and publish docs for data export API/process

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1199]
## User Story
As a Koku end user, I want to know how to use the data export API so I can get my files and do my own data processing.

We need to work with Dayle to author some docs around this API. We also want to publish the docs to readthedocs.org periodically.

## Assumptions and Questions

- Do we just release this with the rest of https://koku.readthedocs.io/ ? Or does this need to go somewhere else?
  - Probably all together.
- Do we document for the end user the general archival process in which we retain our copies? Or do we only document the user's workflow?
  - Probably only the latter (user workflow).

## Acceptance Criteria

- [ ] Docs exist and are regularly published at readthedocs.org
- [ ] Docs include:
  - [ ] How the user needs to configure their destination S3 bucket.
    - they need to grant write access for our AWS user/role
  - [ ] Examples usage

**Comment by infinitewarp** [comment]
This should include an explanation of how the customer should set up their new S3 bucket with appropriate ACLs to allow koku to write files to it.

**Comment by infinitewarp** [comment]
I'm removing my assignment from this issue and putting @dayleparker in my place. She and I have been chatting over Slack and Google Docs to shore up her version of the docs, and I'll continue to be available as needed to clarify, but I'm henceforth "passing the baton" for someone else to ensure that this gets completed. Cheers! :wave:

**Comment by dayleparker** [comment]
No worries Brad! Thanks for all your work on this. The version of the doc I've been working on is here: https://github.com/project-koku/koku-doc/tree/master/downstream/titles/exporting_data_using_the_API

Just need to do a few more things to ensure it gets published for Koku readers...

**Comment by dayleparker** [comment]
OK, let's call this item done as the doc is published: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/exporting_cost_data_using_the_api/index

The source lives here: https://github.com/project-koku/koku-doc/tree/master/downstream/titles/exporting_data_using_the_API

However, it's not consumable in a nice 'readthedocs' way for Koku. Please feel free to reopen if this should be a completion criteria -- otherwise we can just tackle this later with moving the rest of the docs upstream.
