### ISSUE TITLE
Spike: investigate deepObject-style `filter` use in generated clients

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1278]
## Problem Overview

Koku's `openapi.json` specifies the `filter` query parameter with the `deepObject` style. This means that clients are expected to generate HTTP requests that look like:

`?filter[foo]=bar&filter[fizz]=buzz`

However, the clients in https://github.com/project-koku/koku-cli generated via https://github.com/project-koku/koku-cli do not seem to support this functionality. For APIs that should support `filter`, the generated clients fail to expand into multiple array-like query parameters, and it seems to generate HTTP requests with only a singular `filter` like:

`?filter=foo`

## Research

Supposedly the IQE tests are also using a generator to produce client code from `openapi.json`, and supposedly they have solved this problem. We need to investigate and see if there is something similar we can or need to do with our generated clients to successfully enable use of the `filter` query argument.

Reach out to @lcouzens for guidance around IQE. Previous conversations I had with Luke include:

https://ansible.slack.com/archives/CAAN6CRB2/p1570550361141600?thread_ts=1570548980.138500&cid=CAAN6CRB2
> So I think there was a better solution coming but I can't  remember. But I just took a look at the hccm_plugin and looks like Daniel just added a basic workaround for now. Effectively append this params to the URL :smile: https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/blob/master/iqe_hccm/fixtures/api_fixtures.py#L1384

https://ansible.slack.com/archives/CAAN6CRB2/p1570550453141800?thread_ts=1570548980.138500&cid=CAAN6CRB2
> then the tests just string it all together like this https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/blob/master/iqe_hccm/tests/rest_api/v1/test_aws_cost_reports.py#L41

## Output

Depending on our findings from the IQE research, at least one of:

- documentation of how to properly use `filter` in our existing generated clients
- documentation of changes we need to make to our generated clients to use `filter` in the deepObject style
- implemented changes (perhaps as prototype) to our generator or the generated clients themselves
- proposals for alternate solutions (maybe to further investigate) if we find no working solutions here

Timebox: 3 days

**Comment by infinitewarp** [comment]
Related notes @katherine-black found for using a generated client in IQE: https://gitlab.cee.redhat.com/insights-qe/iqe-tests/blob/dc330a5459f83910074b476440d07797cbf0f14f/docs/rest_client.md

**Comment by katherine-black** [comment]
Unfortunately the resolution for this spike will be `proposals for alternate solutions (maybe to further investigate) if we find no working solutions here`, and here is why.

While QE and koku-cli-generator both use https://github.com/OpenAPITools/openapi-generator, and QE has come up with a workaround for the client not supporting array query params, this solution is not really feasible to give our customers. Currently, QE gets around this issue by constructing the query params with python, and making a "raw" call to the api, not using actual client functions. As such, that isn't something we can expect our clients to do.

```
how this is handled in iqe

call to generate params: https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/blob/master/iqe_hccm/tests/rest_api/v1/test_aws_cost_reports.py#L38
api_params_to_encoded_string: https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/blob/master/iqe_hccm/fixtures/helpers.py#L365
and call_api_raw: https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/blob/master/iqe_hccm/fixtures/helpers.py#L389
```

So what potential solutions do we have? Well, for one we could wait for the implementation detail discussions to end, and the functionality to be added to the generator. How long this will take is unknown. https://github.com/OAI/OpenAPI-Specification/issues/1706 has been around for a year, with no resolution really in sights. And while deepObject serialization has been added back in March via https://github.com/OpenAPITools/openapi-generator/pull/2234. One notable part of that PR is the following:
```
This method does not support arrays of objects, as this would cause an ambiguous serialization due to the use of the explode format for arrays.
E.g. a query string person[name]=Alice&person[name]=Bob could be interpreted as an array of person objects with one name property each, or one person object with an array property name.
```

So it does not seem like we'll have a generator provided by openapi that can handle this functionality. 

What does that leave us with? This is where we need more discussion with the team. 
Do we roll our own generator? This would be a potential solution, but it seems like we'll be largely reinventing the wheel. 
Do we abandon deepObject filters in koku? This _is_ a feature that's supported by a lot of frameworks, so it doesn't seem like we are just taking a bite out of something that's too cutting edge, it's just that OAS doesn't seem to be 100% there yet. So abandoning this doesn't quite seem right either. 

I should also add that a wrapper doesn't seem like a good option, and if anything, the client code would have to be patched in some way after being generated to add this functionality, due to how the client limits params it doesn't recognize. This sounds like extremely tight coupling and could lead to a lot of failures.

**Comment by infinitewarp** [comment]
Thanks for the detailed findings, @katherine-black ! I think we can close this issue now and have further discussions elsewhere about deciding on and proceeding with next steps.
