### ISSUE TITLE
Keep Only Current Month Line Item Data

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1616]
**Describe the bug**
We recently made a config change to keep less raw data in the DB. Removing previous months data deletes our summary tables for that time period. If we want to keep less raw data, we either need to modify the expired data remover or update our DB models for the summary tables' on_delete option to not delete the summary tables when a bill is deleted. 

**Expected behavior**
We should be able to remove raw data and still display the summarized data in the UI

**Assumptions**
- Short term update e2e to have a 2 month config. [Done]

## Additional Information
- The Expired Data Remover class: https://github.com/project-koku/koku/blob/30208f4ccfd80db2270d6e523b0343d5d6139b19/koku/masu/processor/expired_data_remover.py#L45
- We essentially want a new method in each source-specific DBCleaner class, similar to the existing purge_expired_report_data, but one that removes all rows from the raw line item table for previous billing periods. 
  - Reference: https://github.com/project-koku/koku/blob/30208f4ccfd80db2270d6e523b0343d5d6139b19/koku/masu/processor/aws/aws_report_db_cleaner.py#L89-L91

**Comment by nbon12** [comment]
Sprint Planning:
Andrew: "Sergio was showing the demo account during the all hands, and was asking why isn't there December data? When we ran out of disk space in the database. I made a choice to wipe a lot of the data there. We have an expired data remover class and celery scheduled task for beginning of every month. We ask it to keep a single months worth of data. Keeping summary data only is great but because of our foreign key usage, if you delete, it cascades and deletes summary data too. I'm inclined to call this a bug. Priority medium because we can fix it soon but in the meantime we can keep that setting to 2 months so we don't delete more. After we do that delete we end up processing the previous month anyway."
Chris: "In the short term we update e2e to have a 2 month config. I don't think it's important to solve this given other things we need to do. It's a good thing to work on but unless we start hitting thresholds again due to huge ramp up, we should be ok for this sprint."
Andrew: "In that case I moved priority to low because we have a quick fix. I'll make a PR right after this"

**Comment by myersCody** [comment]
I have finished up the base of this issue, but still need to complete a part 2 essentially described in this comment by Andrew: https://github.com/project-koku/koku/pull/1727/files#diff-ceaeef4fc79d087d75a0859bd17d6b87R82

- [ ] Complete part 2

**Comment by lcouzens** [comment]
Verified
