### ISSUE TITLE
AWS EC2 instance counts should be param gated

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1618]
## User Story
As an API user I want instance counts to only return when I request them so my response times on queries are fast. 

## Assumptions
- The AWS instance_type API always returns instance counts today.
- The UI does not display instance counts anywhere today
- Because this is an expensive operation we should require an `count=True` param to run this calculation

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/cost-management/v1/reports/aws/instance-types/?compute_count={true/false} |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ] Instance counts are only returned when the count param is set to true.

**Comment by nbon12** [comment]
Sprint Planning Meeting Minutes:
Andrew: "Right now in the AWS instance type API always returns instance counts today. It's an expensive thing to calculate when you're doing the daily API call, the daily resolution. The problem is when you aggregate the instances you've seen each day, you can't just sum those and expect it to be the monthly total. You may have seen 5 today and 5 yesterday, you can't make assumptions as to which ones were the same from yesterday. The way we do this is re-calculate and that's super expensive. I don't think we display instance counts anywhere today.
Natalie: "Don't we show that on the dashboard?"
UI Dan: "No we don't, we show the cost of EC2 usage."

Andrew: "We don't set instance counts unless the count param is set to true. That instance type API takes longer than others, it goes over the 2 second mark."

**Comment by kholdaway** [comment]
so the param count collides with pagination params.  I am going to name it compute_count in the PR

**Comment by kholdaway** [comment]
MR for IQE tests.  Still working on running linting locally.

https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/merge_requests/503

**Comment by lcouzens** [comment]
I think there might be some additional failures in IQE looking at our smoke job results  https://ibutsu.cloud.paas.psi.redhat.com/results?metadata.run[eq]=5e3bda6710e97eaad85a48af&result[eq]=failed&page=1&pageSize=20

**Comment by lcouzens** [comment]
I have an MR with the additional fixes, also I noticed the tests you fixed were failing too but thats just because we didn't tag and release the plugin :D

**Comment by lcouzens** [comment]
Verified!
