### ISSUE TITLE
Project name is surrounded by brackets

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1650]
**Describe the bug**
While testing tag filtering, I noticed that the project name has brackets around it. For example, `"project": "{cost-management}"`. This seems odd because we don't see brackets with other requests.

**To Reproduce**

With this example, I'm grouping by tag, project, and cluster

/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[and:tag:app]=cost&group_by[and:project]=cost&group_by[and:cluster]=cost&order_by[cost]=desc

See the brackets around project name
![Screen Shot 2020-01-27 at 11 19 44 AM](https://user-images.githubusercontent.com/17481322/73193139-1a910480-40f8-11ea-9162-7eef56fe8a01.png)

With this example, I do not see any brackets.
/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[project]=*&order_by[cost]=desc

![Screen Shot 2020-01-27 at 11 23 29 AM](https://user-images.githubusercontent.com/17481322/73193242-3d231d80-40f8-11ea-9ac3-4c23823c4fe8.png)

**Expected behavior**
Not expecting brackets around project names.

**Notes**

Because the first group by is not `group_by[project]` projects are being returned in an array. (See the OCPAWSDailySummary table model to confirm the array type). There is also a group by project here, so we probably need to return the single project name outside of an array in this case.

**Comment by nbon12** [comment]
Sprint planning meeting minutes: 
Andrew: "If you look at grouping happening here, this is an openshift on infrastructure API, the thing here is, pretend this is AWS, the view here is looking at the cloud provider and infrastructure provider data, if we're looking at AWS it's possible it can be used by multiple openshift projects, it's a many to one relationship, so we cant store in that table uniquely by AWS costs and uniquely by openshift, so projects get rolled up into an Array in that table. If you did a group_by project first, that would break it down by projects, everything else gives you a list. But the fact that you are also specifying a group_by project: we might need to handle that differently, because it's an array, this might be another special case we need to handle. because you have a group_by[project] in here, if it were the first it wouldn't be an array. When you group by project first, it gives the project cost of things, when we first started doing all of this we had this formula that says we know, for example, for CPU we know a project is using this much CPU so a calculation causes project cost, there was a product decision that when you group by project is a special case, so re-arranging those group by gives a different project cost. Ordering matters with project, group_by project shifts the perspective and looks at it from the openshift perspective.  From a User standpoint they should be allowed to group by whatever order they want so I think we should fix this."

**Comment by chambridge** [comment]
So the materialized view used in this lookup seems to have bad data:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/29379759/73563292-fd777100-442a-11ea-9dda-de4c7545337c.png">

Namespace column contains the following: `['analytics']`

**Comment by chambridge** [comment]
So it looks like its not selecting the right report.

Looks like the is the offending line of code:
https://github.com/project-koku/koku/blob/master/koku/api/report/all/openshift/query_handler.py#L40-L41
```
        if (group_by and group_by.get('project')) or \
                parameters.parameters.get('filter', {}).get('project'):
```

As the incoming group by data looks like this:
```
group_by=OrderedDict([('and:tag:app', ['cost']), ('and:project', ['cost']), ('and:cluster', ['cost'])])
```
The code is not properly handling the potential boolean logic.

There are a few other hits of this kind of issue also:
https://github.com/project-koku/koku/search?q=%27_by_project%27&unscoped_q=%27_by_project%27

Will look to clean these all up with a utility method.

**Comment by lcouzens** [comment]
Verified
Commit: de6004607a845898ca36b4e1e573efe37a47096b
