### ISSUE TITLE
Adding Provider should trigger a task to download data.

### ISSUE THREAD

**Issue by maskarb** [project-koku/koku#1691]
## User Story
As a customer I want to see data as soon as I add a Source/Provider. Currently, when we add a source, we must wait until a scheduled tasks kicks off and fetches data.

## Acceptance Criteria
- [ ] Adding a provider causes a data download task to begin.

**Comment by nbon12** [comment]
Sprint Planning Meeting Minutes:

Andrew: @maskarb is already investigating this but we might as well refine it. Even 30 minutes later it can be blank, and we're not sure if it worked. Some of that is for a large customer, if it takes hours to download and fully process a report, it's going to be a while before we have data in there, I'm not sure if that's something we can really fix, but if it's someone trying the tool out, or a small customer to see if small examples work, for Cloud Accounts, it would be nice to trigger the download and process workflow as they add it, instead of waiting for the next time that thing runs, because in production right now, that's 12 hours, so that can be messy.

Chris: For a good user experience, look potentially at how the UI can show the status of the providers from the stat stuff, that came out from the openshift dedicated team not knowing we weren't gathering their data because we ran out of storage.

**Comment by lcouzens** [comment]
Verified
