### ISSUE TITLE
Celery task checking does not cross pod boundaries

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1693]
## User Story
As a celery worker I would like to know which tasks are running across worker pods so that I do not duplicate work. 

## Impacts
Worker

## Assumptions
-Today we have logic that uses celery's `inspect` ability to check for registered tasks. Unfortunately this does not cross pod boundaries, so we end up retrying tasks in other worker pods. 
- We want a consolidated location to check for running tasks (redis?)
- We want to use the manifest ID as the thing to check if we are already processing a report.
- If we are processing a manifest for a current source and a newer manifest comes in, we don't want to be processing both at the same time.  

## Acceptance Criteria

- [ ] A worker checks the cache of task IDs to see if we are running that task in any pod.

**Comment by nbon12** [comment]
Sprint Planning Meeting minutes:

Andrew: Workers in multiple pods, no networking, so it's pre-container style. We want some way of consolidating that check across pods. I'm proposing we use Redis since we already have that running in our openshift environment. Each worker would send up the tasks it's working on into the combined Redis space. Before kicking off a task they would always check that location. The potential con is that if Redis goes down, this isn't totally fail-proof. We were running a task more frequently than it was taking that task to complete. For example openshift dedicated tasks were taking longer than 4 hours. After that 4 hour period we would kick off the next task. Another celery worker would pick up on one of the tasks that wasn't done and then it would duplicate the data that the other worker was doing. We have this temporarily handled by switching the task time to 12 hours instead of every 4 hours so we should be covered for now but we still want to fix this. 

Michael: The task that's looking for things to download, is that the same task as the task that processes the files or is that a separate task?

Andrew: We have a stateful set situation so we cannot split the tasks, if we split the task, celery will not guarantee which worker will do a task, if the task happened in a pod different from the one that downloaded, we cannot share the volume across workers. Today it's one mono-task. The tasks are tied together.

Kevan: What's the unique ID used to identify?

Andrew: Celery generates a task UUID.

Kevan: Do two different celery pods generate the same UUID for the same work?

Andrew: That's worth investigating. There's a manifest ID that we're pulling from AWS or generating ourself, that's the collection of report files for this download. We don't want to double process this, the next time a more recent manifest, we don't want the workers to step on each others toes when a delete happens, etc.

**Comment by adberglund** [comment]
@lcouzens If you look at my functional testing results on https://github.com/project-koku/koku/pull/1746 this one really requires 2 workers to allow multiple tasks to run at 1 time. Basically if we run a download task for a provider, and then immediately trigger another the 2nd task should be blocked from running because the other worker is already running a task for that provider.

**Comment by lcouzens** [comment]
Verified
