### ISSUE TITLE
Provider delete calls can take too long

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1697]
## User Story
As a user of cost management (and platform sources) I want the deletes of providers to be fast, so that the application does not appear to hang.

## Impacts
API, Sources integration

## Role
Backend

## Assumptions
- Right now we make use of Django's on_delete which goes and deletes all of the tenant reporting data for the provider: https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.ForeignKey.on_delete
- We could make use of a post delete / post request signal instead to make sure the appropriate data is deleted, but after the provider DELETE call returns. 
  - https://docs.djangoproject.com/en/3.0/ref/signals/#post-delete
  - https://docs.djangoproject.com/en/3.0/ref/signals/#django.core.signals.request_finished

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | DELETE |
 | **Path** | /api/v1/providers/{uuid} |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ] Provider deletes return immediately after the provider model is deleted
- [ ] All relevant tenant data is removed.

**Comment by nbon12** [comment]
Sprint planning meeting minutes:

Andrew: When now it can take longer than 5 seconds. When a provider delete call comes in, it cascades deletes through all the tenant reporting data. That becomes one operation that does not release the response until all that's done (synchronously), we could delete the provider, change those on-deletes to not actually cascade, but on a POST have a delete signal clean up the rest. There's also an open question around should we still use the providers table as our source of truth for sources? Or do we want to modify things around. We might want a conversation on that before doing this work. 

Chris: I moved a bunch of stuff that happens in the POST delete, as to where it is, it doesn't affect any cascade, but a lot of things like cost models were not cascaded because some of those things could be shared. We might re-visit this once we re-visit whether this is a performance thing anymore. If we deprecate providers endpoints, and go through sources, sources is fast because it fires-and-forgets. The latency issue would go away because it would be on sources.

**Comment by blentz** [comment]
The provider endpoint was one of the slower endpoints I saw when looking into #1707

It definitely needs some attention.

**Comment by adberglund** [comment]
@chambridge Since you are working on the provider -> sources API switch, I think now what we want is just to make sure the provider delete doesn't cause the sources delete to hang.

**Comment by nbon12** [comment]
Sprint planning meeting notes:
Andrew: "The problem was that when you delete provider it causes a cascade of deletes in tenant schema of provider. It waits for those deletes to finish and when you're making an API call that was taking upwards of 5 seconds to roll through. @chambridge has been working on transitioning us to using the Sources table in our APIs and having the Sources endpoint be the way we interact with Sources. Provider's API is to go away, so it won't matter how long it takes."
