### ISSUE TITLE
Utilize materialized views for OCP on AWS report queries

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1702]
## User Story
As a customer running a large OCP footprint on AWS I would like OCP on AWS reporting queries to return quickly at scale, so that when viewing the dashboard the experience does not suffer from long request load times.

## Impacts
API

## Assumptions
- We will need to select the right model for the query handler based on the query: https://github.com/project-koku/koku/blob/2879d253f1bc8daee5f67bddc8709f3120408f26/koku/api/report/aws/query_handler.py#L120

## Implementation Details
Changes should be modeled on the following PRs that added materialized views for AWS queries:
https://github.com/project-koku/koku/pull/1495
https://github.com/project-koku/koku/pull/1554
https://github.com/project-koku/koku/pull/1645

## Acceptance Criteria

- [ ] Verify that existing test cases (unit and QE) still pass
- [ ] Views exist for cost, 
   - reports/openshift/infrastructures/aws/costs/
   - reports/openshift/infrastructures/aws/costs/?group_by[project] 
   - reports/openshift/infrastructures/aws/costs/?group_by[cluster]
- [ ] Views exist for compute API
   - reports/openshift/infrastructures/aws/instance-types/
- [ ] Views exist for storage API
   - reports/openshift/infrastructures/aws/storage
- [ ] Views exist for database API
   - reports/openshift/infrastructures/aws/costs/?filter[service]='AmazonRDS','AmazonDynamoDB','AmazonElastiCache','AmazonNeptune','AmazonRedshift','AmazonDocumentDB'
- [ ] Views exist for network API
   - reports/openshift/infrastructures/aws/costs/?filter[service]='AmazonVPC','AmazonCloudFront','AmazonRoute53','AmazonAPIGateway'

**Comment by nbon12** [comment]
Sprint Planning Meeting Minutes:

Andrew: For AWS we put in materialized views specific to the dashboard. We have some annoying logic around checking what group_by or filters have been used to determine which materialized view or summary table to use. The larger daily summary table is still used across many. As we're allowing more complicated group_by and filters, we need a better option.  This fits nicely into what @Red-HAP has been working on with Nise data generation. I wrote this story because we talked about general performance. This is the first place to hit once the data generation is in place. Not timing out would be a big first step.

HAP: all the large data generation I did was for OCP the only question is that if I focus on that locally is that analogous to the AWS tables or are those models too different?

Andrew: I suspect that you might see some of the same things, for instance the date filters we make a date call, so that index might not be being used, if that were happening that might be similar across all of them. The openshift has fewer things you can group_by and less information in general so it's not bad to work through openshift one first, and then take lessons learned there and apply them here as well.

HAP: for OCP I got 946,000 rows into the summary table.

**Comment by lcouzens** [comment]
Verified
