### ISSUE TITLE
Support Tag Inheritance with OpenShift

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1713]
## User Story
As a customer, I want to apply labels in OpenShift for cost management more efficiently, so that I can communicate common labels like cost center, environment type, etc. without needing to apply these labels to every pod.

## Impacts
- Worker

## Assumptions
- A label applied to a node will be inherited by the pods running on that node
  - We want to load data into the database unaltered and do our node -> pod label change step in the daily_summary SQL file when we do other conversions. 

## Implementation Details:
 - OCPReportProcessor needs to load in node labels
 - OCP tables will need to be updated with node labels
 - OCP Summary Updater will need to apply node labels to pods
  - This can be done in the https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpusagelineitem_daily.sql and https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpstoragelineitem_daily.sql
   - This should automatically be applied to tag summary tables if done on the daily table.
 - We should evaluate the OCP Report Processor for now it decides if a report is pod/volume and make sure we are either more flexible or allow older reports to still be processed.

## Acceptance Criteria
- [ ] Node labels are ingested and stored in the line item tables for usage and storage
- [ ] Node labels are applied across pods and volumes when queried by the reports APIs
- [ ] We still accept legacy reports that do not have node labels

**Comment by nbon12** [comment]
Sprint Planning:

Andrew: This is good priority because it's important for cost model work and tagging work. This is a korekuta issue, impacting operator metering. A label applied to a node in openshift would be inherited to the things using that. The links in this issue step through how operator metering works. The first thing you would do is to make a data source (from prometheus), the metrics importer query, kube_node_labels is probably the thing, duplicated for node_labels. Next step: the ReportDataSource we would want to break down labels we're getting, break down the node and the labels. Next step: incorporate it into the reports we're pulling. One thing we can do is that we'll want to add the node labels as data we're bringing in. We need to be able to do group_bys which differentiate nodes in different labels. As far as making it apply to every pod, we can work that magic on the presto side with operator metering, or when we're ingesting data we can also apply all the node labels to a pod.

Chris: We need the node labels for things like cost model. We talked about keeping the purity of what came from the source. We should probably do that mapping within our worker so we could always turn it off and there wouldn't need to be an operator update, it would all be on the SaaS side, which makes the Korekuta part easy and it's the thing that actually maps the node labels into the pod labels. 

Andrew: That modification was historically in our sql

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

Andrew: "This is the koku version of a korekuta story. From the worker side of things we want to load in the node labels that we get from korekuta. The openshift summary updater, as a concept we're pulling node labels from prometheus, and if a node is tagged with something we want that to trickle down to all nodes on that pod. The place to do that is in our Reporting OPC Usage Line Item Daily SQL files, then if we do it there we'll automatically get the tag applied. Node labels are ingested and stored in the line item tables for usage and storage. "

Chris: "When we're identifying reports coming in through listener, we do it by looking strictly at columns that are there, are we introducing an additional report or are we injecting node labels onto a pre-existing report? That has an impact on how we do the korekuta version [of this story]. I could easily say to throw it onto pod report of CPU and Memory but then we'll start missing older reports that don't have [that]." [Or we could be less strict on the memory and CPU usage report.]

**Comment by lcouzens** [comment]
Verified!
