### ISSUE TITLE
Implement new cost model terminology in report APIs

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1762]
## User Story
As an API user I want the cost values returned by reports to be consistent with cost's documentation and UI so that I can understand the returned data.

## Implementation Details
We want our cost terms to conform to this structure: https://docs.google.com/document/d/1hnwS0uwPuAKw75QyE2QEl8IZcczaQredMvDY10UVhLk/edit#heading=h.vni94y2bx1hl

## Impacts

- API
- UI
- Testing

## Acceptance Criteria 
- [x] All reports APIs return cost data using the above specified format.

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

Andrew: "We might want to do this before the other cost model stories. "
Chris: "Sooner rather than later because of how disruptive it will be to everything, [it impacts] API, UI, Testing. The only problem with not doing this first is that it makes it harder to test, if things aren't going into correct named bucket, then Luke would have to either wait for this to be done. This is a precursor to know that [the report API] is working correctly."

**Comment by lcouzens** [comment]
Verified
Tests updated and passing! Thanks guys.
Commit: d03186799552886a92b9aca7ff914404ac0a8f4b
