### ISSUE TITLE
Monthly cost calculations should respect date ranges

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1774]
## User Story
As a user I want cost models calculations to be consistent across different cost types so that I have a unified experience. 

## Impacts
Worker

## Assumptions
- There are two monthly cost methods in the OCPReportDBAccessor that should respect a start and end date
  - https://github.com/project-koku/koku/blob/b3d4ff79d24df9182c2e2a752344e3d606a5dd12/koku/masu/database/ocp_report_db_accessor.py#L627
   - https://github.com/project-koku/koku/blob/b3d4ff79d24df9182c2e2a752344e3d606a5dd12/koku/masu/database/ocp_report_db_accessor.py#L698
- We should not query for max/min usage_start dates 

## Acceptance Criteria

- [ ] These methods require a start_date and end_date and use those specified date values
- [ ] No regressions in monthly cost

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

Andrew: "Remove monthly cost [currently] blanketly removes everything. This is inconsistent with the rest."

Brett: "Do we want to make decisions on whether the db accessors should stay or go, or whether all koku should use them, or they [should be deleted?]"

Andrew: "In my opinion they're not harmful. They are less direct, as a layer of database middleware. If you know the Django ORM it's convenient to call directly but it's a pattern we use across the database, for example we have Date helpers instead of using datetime directly."

Brett: "I might throw an issue into the backlog to have that discussion."

**Comment by adberglund** [comment]
This should have been handled as part of https://github.com/project-koku/koku/pull/1828

**Comment by lcouzens** [comment]
Verified
