### ISSUE TITLE
Easier Deploy

### ISSUE THREAD

**Issue by stobias123** [project-koku/koku#1779]
## User Story
As an openshift user, I want an easier installation process leveraging native kubernetes resources, so that I can more simply use this project.

## Impacts
API, UI

**Comment by blentz** [comment]
This is a request that we'd like to accommodate. 

@stobias123 - can you give us a little more detail about what works / doesn't work for you, and what you'd like to see?

Some background and general info:

Koku is the upstream open source project for a cost management service Red Hat is running as a SaaS as part of the Red Hat Insights initiative. We've got some implementation details that may present their own challenges when trying to run Koku outside of the target environment. 

However, we do want to support community contributions as much as possible. So, if we can add documentation or arrange things to help you contribute more easily, we'll try to make that happen.

**Comment by stobias123** [comment]
@blentz  - thanks for the response. I had some suspicions about where koku was used, I'd love to give it a shot self hosted! 

There's a couple areas I've had some challenges with koku in the past and with my recent setup attempt.

1. Last time I tried to install it wasn't tested on openshift 4.x? (I could be wrong here)
2. Dependence on `make` tooling is abnormal for k8s projects.
3. Heavy reliance on openshift native resources makes installing on vanilla k8s challenging.. 
4. Helm install (or operator) would be nice

Really I think just creating an operator or helm chart would solve all my above complaints. :)

**Comment by blentz** [comment]
@stobias123 - I think we can work with that. Also, definitely keep an eye on this year's Red Hat Summit. :slightly_smiling_face: 

To address your points:

1. OpenShift 4.x is a new target for us. We were focused on 3.x for quite a while, but we're in the process of shifting over to supporting 4.x. (See, for example, #1695 ) It's in progress, so we'll likely have more on this in the coming weeks.

Also, our backend deployment processes rely on things that live in non-public repos. So, some of how we deploy to our current environments requires having access to internal RH resources. We're working on making sure as much of our code as possible is OSS without exposing things like service passwords and the like. But, it's still early in our lifecycle. A lot of these things aren't "set" yet. :slightly_smiling_face: 

2. The `make` tooling is because it's something everyone on the initial development team understood. It was just the lowest common denominator for us. Most of us are still learning what the K8S best practices are. So, if that's something you're interested in helping us better align with the upstream communities, we're open to suggestions.

3. Our deployment target is OpenShift (3.9+ and 4.x), so that's why you're seeing the templates are OpenShift-specific. However, you've caught us in the middle of transitioning to a new workflow. The templates that are in the `openshift` directory in the repo are considered deprecated. The newer workflow that we've been working on and more actively developing is exposed by the `scripts/e2e-deploy.sh` script. That references some non-public repos, unfortunately. 

4. Once we get a bit further along on #1695, I think we can probably see what's left to support Helm or a native k8s deployment. Or, if you feel up to helping add that support, i think we can get you the info you'd need from us to do it. I hang out on Freenode with the same username, so feel free to ping me there if you want to dive in.

**Comment by chargio** [comment]
Aligning with the upstream communities and making sure that Koku is deployable is one of our goals for the open source community @cybette.
Any help to make this happen would be greatly appreciated. There are some dependencies on the underlying platform in which we deploy that do not belong to the open source deployment

**Comment by blentz** [comment]
Here is a recent OpenShift Blog article discussing the Cost Management service (aka Koku): https://blog.openshift.com/tech-preview-get-visibility-into-your-openshift-costs-across-your-hybrid-infrastructure/

This should help provide additional context :slightly_smiling_face:

**Comment by ThinkBriK** [comment]
> Aligning with the upstream communities and making sure that Koku is deployable is one of our goals for the open source community @cybette.
> Any help to make this happen would be greatly appreciated. There are some dependencies on the underlying platform in which we deploy that do not belong to the open source deployment

Community won't be able to help as you're using RHEL images to build the product. You should at least provide an alternative (UBI or Centos) in the imagestreams used to build the containers.

**Comment by chargio** [comment]
Using UBI would make sense

**Comment by adberglund** [comment]
I have opened https://issues.redhat.com/browse/COST-252 to track this issue. We have moved issue tracking to a public Jira instance and are closing out GitHub issues in favor of tracking there.
