### ISSUE TITLE
AWS price lists and notifications

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#18]
As the system, I want to have access to the generic price lists for comparisons. And keep a historical database of them so I can recalculate costs.
As a user, I want to download the current price list from AWS so that I can calculate my costs.
As the system, I want to set up SNS to be notified when the price list changes
As a user, I also want to set up SNS to be notified when the price lists changes

## Acceptance Criteria ##

- [ ] Verify that the price list is downloaded and updated
- [ ] Verify that the overall price list still exists, and that the proper one is used
- [ ] Verify that there can be more than one price list per CMaaS user (as different accounts can have different price lists)
- [ ] Verify time limits for the price lists are correct.
- [ ] Verify that the user can configure the SNS service so CMaaS is notified when the price list is updated
- [ ] Verify that the price lists cover all times (i.e. there is no missing price list when one is applicable in April, and the next one is applicable from June onwards)

## Assumptions and Questions

- Assumption: the AWS price lists includes all definitions needed for charging (inc. tiers and discounts)
- This user story does not mandate where to store the information
- Question: does all price lists get updated at the same time or any customer can get updated price lists at different times?
- Question: What is the most efficient way of getting the information we need?
- Question: Do you need authorization to get an specific user price list?
- Question: What happens when the user does not have a price list specific for him? And when that changes and he received an offer?

#### Service Endpoint #####

AWS Price List Service API provides the following two endpoints:

https://api.pricing.us-east-1.amazonaws.com

https://api.pricing.ap-south-1.amazonaws.com

#### Granting IAM Permissions to Use the AWS Price List Service API ####

An IAM user must be granted explicit permission to query the AWS Price List Service API. For the policy that grants the necessary permissions to an IAM user, see Example 11: Find products and prices.

**Comment by adberglund** [comment]
Pricing is available via boto3: http://boto3.readthedocs.io/en/latest/reference/services/pricing.html

This may not be our route, but it may come in handy. An initial thought is perhaps we use the bulk API to pull a full price list when starting out. Then we use SNS/SQS notificatons + the boto3 pricing api to pull price updates.

**Comment by blentz** [comment]
Here's an old script I wrote (using Pyramid) that pulls the pricing data into a SQL db using sqlalchemy:
https://github.com/blentz/cloud-costs/blob/master/budget/scripts/aws_pricing_data.py

It's somewhat purpose-built for a specific task, so I'm uncertain how reusable it'll be. But, it may be helpful as a guide. 

The pricing data is heavily nested, particularly for EC2, so we'll need to spend some time on building a data model that stores this data in a way that makes sense for our use case.

**Comment by blentz** [comment]
Question: does all price lists get updated at the same time or any customer can get updated price lists at different times?

Price lists are service-specific. So, the EC2 price list can be updated independently of the S3 price list or the SES price list.

Question: What is the most efficient way of getting the information we need?

An HTTP 1.1 GET request. We can use eTags to identify whether the data has changed or not. Which means we'll need to capture the eTag for each price list, along with a timestamp.

Question: Do you need authorization to get an specific user price list?

AFAIK, there are three discounting mechanisms to be aware of:

1. AWS Enterprise Discount Program: https://aws.amazon.com/pricing/enterprise/
2. Volume-based discounting: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/useconsolidatedbilling-discounts.html
3. Reserved and Dedicated Instances: https://aws.amazon.com/ec2/pricing/reserved-instances/ and https://aws.amazon.com/ec2/purchasing-options/dedicated-instances/
 
Question: What happens when the user does not have a price list specific for him? And when that changes and he received an offer?

This will need to be a combination of 

1) deducing costs based on available data (e.g. we can scan for RIs) and 
2) user-input - the user can tell us what their EDP discount percentage is and 
3) issuing a disclaimer that our numbers are based on what we know or can infer, but we can't guarantee 100% accuracy. This is especially true in the current month, prior to invoice finalization where most of these discounts are applied. All of the usage numbers AWS gives us are classified as "estimates" until the month closes and the invoice is finalized. The CUR (Cost Usage Report) for previous months is going to be more accurate than the estimates we can deliver for the current month. Often, the delta is going to be very small (<1%) but I've seen cases where the final invoice differs from the current-month estimates by as much as 5%, and a couple rare cases where it was off by more.

**Comment by chambridge** [comment]
Portions of this story will not be covered in the initial release work and will be moved into Aha!

The necessary capabilities needed for the initial release have been included into other stories. Closing this larger item.
