### ISSUE TITLE
Enable Setting to Select OpenShift Tag Keys to Summarize On

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1833]
## User Story
As a customer, I want to curate the set of labels used to summarize and filter on from OpenShift, so that I am not bombarded with useless labels that also slow down my report queries.

## Impacts
- API
- Docs

## Assumptions:
- Our settings API can generate the necessary forms driven fields needed for the settings API

## Implementation Details
- The platform introduced application level setting with the following application:
https://github.com/RedHatInsights/settings-frontend

- We need to create an API endpoint /api/cost-management/v1/settings/ that correctly handles the GET and POST conditions needed to store the filtered set of OpenShift tag keys.

- The GET will return JSON that creates Data Driven Forms. These forms would include the current set of enabled tag keys, all available tags (multi-select or table with check boxes?)

- The POST passes back the new set of tag keys for summarization.

## Acceptance Criteria:
- [ ] Verify that Cost Management shows up in the Application level settings
- [ ] Verify that the user is presented with a form with all existing OpenShift tag keys
- [ ] Verify that the user can save OpenShift tag keys to be summarized
- [ ] Verify that visiting the setting after the initial setup presents the user with a way of knowing what tag keys are currently enabled.
- [ ] Verify that updating the tag keys changes the enabled list (add new and remove existing)

**Comment by adberglund** [comment]
We can iterate on this and build out the backend infrastructure and APIs immediately. We will need input from @nlcwong on what the UI should look like via Data Driven Forms (see https://github.com/RedHatInsights/settings-frontend)

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:
Andrew: We did Node and tag inheritance stuff. That was a precursor to some of this work. Now we're getting to a point where we give the users the ability to select a subset of the openshift tags they want to use for summarization. We need some input from @nlcwong on what we should be telling the data driven form to build. This is tag settings, for the data driven forms. I think iterating on this is a great idea. There's a lot of back-end work we can lay the foundation and then change the json. 
Natalie: Why do we need Data Driven Forms?
Andrew: That's the settings endpoint Insights Uses.
Chris: This is for Application Settings.
Andrew: This would be creating our application settings.
Natalie: What would we have in Settings?
Andrew: Tag keys that we want to summarize for on OpenShift. It's configuration Settings. Since we no longer have Preferences API, we now have an Insights Platform-driven Settings. We want to be using their Settings.
Natalie: So if you click on the Cog and go to Settings we have a page of all the Tag Keys?
Chris: Yes, this enables or disables exporting for an account, and other Application settings. This is unrelated to sources. This is tag management. 
Andrew: If a user has a thousand tags in their openshift cluster. If we had to do summarization on all that we'd blow up.
Chris: There's a number of generated labels from OpenShift itself that mean nothing to user so if they can filter out those so they don't see them that would be better for the user experience.
Natalie: How many tags would they have to interact with on average?
Chris: No average, it's dependent on the cluster and how many applications they run there, there could be 
some running thousands, and other running the bare minimum. 
Brett: In the wild I've seen environments where people wire up continuous integration system to do automatic tagging and deploying. So depending on how aggressive they are with that, Jenkins can auto-create a tag for every build it does, and that could sprawl rapidly. The common use case is that most Orgs are 100 tags or less, and there's unique environments that do weird things that we'd never anticipate. 
Andrew: From 2 internal lighthouse customers we saw: GPTE was making a new tag key for every user instead of a tag key that had a different value.

**Comment by adberglund** [comment]
This is somewhat interdependent with #1834 in that to set whether a tag is enabled we need the new enabled column specified in that story.

**Comment by chambridge** [comment]
@nlcwong We can do something like the following:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/29379759/76036719-dd980900-5f12-11ea-802b-f0a5404222f8.png">

The down side with data driven forms is we will likely not have a great experience with a large number of tags.

I'm also trying to use the following: https://data-driven-forms.org/others/miq-components#duallistselect

But currently this component doesn't appear to work in settings, I've asked the platform team for further details.

Natalie, I think its your call as to whether we will need to work with the platform team to wire in our own page underneath application settings so we have finer control. But we can always iterate as well. For now we should be able to get something done, but its what do we want to support longer term.

FYI @adberglund @chargio

**Comment by chambridge** [comment]
I opened the following issue for the dual list select: https://github.com/data-driven-forms/react-forms/issues/358

Richard from the sources team is looking at it.

**Comment by nlcwong** [comment]
@chambridge Is the intent of this tag management feature, to eventually become a tag management service at the platform level or are we envisioning tag management JUST for the cost management application?

If it is just for cost, then I would suspect that we would have our own sub-section under Settings and that would give us finer control on how to produce the page content of that sub-section.

**Comment by lcouzens** [comment]
@chambridge is this complete? I see we have the application tag settings in the UI, but they don't seem to have any affect on the reports in cost-management. Or was this just a first pass to get things in place before it goes live and starts affecting report groupings/filters?

**Comment by chambridge** [comment]
Its an initial step, working on this issue next https://github.com/project-koku/koku/issues/1834 which effects the returned tag keys for OCP. Then lastly there is this story to effect cost summarization: https://github.com/project-koku/koku/issues/1835.

**Comment by lcouzens** [comment]
Verified changes so far.
