### ISSUE TITLE
Sometimes VACUUM FULL 

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1998]
## User Story
As a user I want API calls not to time out so I can access my data.

## Impacts
- Worker
- Database

## Assumptions
- We have this task to vacuum tables https://github.com/project-koku/koku/blob/407b76c7529d06922f451e9674e82fe302faaaf3/koku/masu/processor/tasks.py#L354
- We should either schedule or add some random chance (maybe approx 1 time a week?) to do a `VACUUM FULL ANALYZE` instead of a `VACUUM ANALYZE`
- We might also consider doing the vacuum full after deleting previous months' data. 

## Acceptance Criteria

- [ ] We vacuum full sometimes

**Comment by Red-HAP** [comment]
Just beware that a VACUUM FULL basically does a table rewrite. It will acquire an exclusive lock during th eoperation, so it will cause transactions to time out and fail.
It may be wiser to run vacuum full only on select tables vs the whole schema.
Plus it will consume more disk space during its run.

**Comment by blentz** [comment]
This is a case study, albeit for postgres 9.6.3, that has some good vacuum tuning ideas: https://aws.amazon.com/blogs/database/a-case-study-of-tuning-autovacuum-in-amazon-rds-for-postgresql/

The RDS Best Practices guide also appears to emphasize tuning the autovacuuming over doing full vacuums: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_BestPractices.html#CHAP_BestPractices.PostgreSQL

I think we may want to adjust the autovacuum settings based on how big we expect the DB to be, so that we know the autovacuumer is running frequently enough to keep up with our rates-of-change.

**Comment by Red-HAP** [comment]
Do we have access to the CloudWatch metrics for production?

**Comment by Red-HAP** [comment]
Also, I agree with Brett. I think we should use the case study as a guide and plan how we tune the autovacuum settings at the DB-level (which will require another reboot :( ) and, from there, tune the settings on a table-by-table bases.

**Comment by Red-HAP** [comment]
My research is mostly done. It can be found [here](https://drive.google.com/file/d/1DKCq9R0mYAb22VSFaZgzKXquJTc8UWor/view?usp=sharing)

**Comment by Red-HAP** [comment]
Attaching some research from 2ndQuadrand [here](https://www.2ndquadrant.com/en/blog/autovacuum-tuning-basics/)
