### ISSUE TITLE
Docs Missing OpenShift installation template file

### ISSUE THREAD

**Issue by matteosan12** [project-koku/koku#2390]
Hi,
In the Installation chapter about OpenShift, there is a missing link file for the deployment template:

"A basic deployment configuration is contained within the application’s **openshift template file**." with a link to "https://github.com/project-koku/koku/blob/master/openshift/koku-template.yaml" that results in a 404 page.

Is the doc in updating status? Or just an error?
Thanks in advance.

**Comment by boaz0** [comment]
Hi @matteosan12 

I believe it was removed in [this PR](https://github.com/project-koku/koku/commit/f61e1f26b37dae0ffb0b8a82082c200217fb0d47).

I think it's because we are no longer supporting this particular setup and running `docker-compose` locally works perfectly fine.
Nevertheless, you can use CodeReady Containers to run this using [`scripts/e2e-deploy.sh`](https://github.com/project-koku/koku/blob/master/scripts/e2e-deploy.sh)

@blentz correct me if I'm wrong.

PS: we don't keep track of Github Issues. Please use [JIRA](https://issues.redhat.com/projects/COST/) to file tickets.

Thanks.
