### ISSUE TITLE
User is not able to log in

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#283]
**Describe the bug**
The button for log in does not work.
Tried using a Mac on Firefox, Safari and Chrome.

**To Reproduce**
1. go to login page
2. Introduce login
3. introduce password
4. press the log in button /  tab and press enter

**Expected behavior**
The user should log in and the application should appear

**Context (please complete the following information):**
 - OS: MacOS X High Sierra
 - Browser:  chrome, safari, firefox
 - Using staging app

**Additional context**
First time the user logs in.

**Comment by chambridge** [comment]
The actual issue here was that the Postgres database was in a bad state and had to be redeployed.  So the issue wasn't that the Login button didn't work, but that error cases like 4XX or 5XX status codes aren't reported back at the login, so even though there was an error talking to the API it wasn't made visible to the user.

Please reopen this against the UI repository, to display these errors.
