### ISSUE TITLE
500 error trying to create customer through api when email service password is incorrect

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#387]
**Describe the bug**
When creating a customer through the api I am hitting error 500, after further investigation I believe its due to supplying a wrong password for mail-gun during deployment.

**To Reproduce**
1. Deploy hccm with incorrect mail-gun password
2. Navigate to api
3. Login to django
4. Try creating a customer.

**Expected behavior**
Customer created or clear error of failure

**Screenshots**

**Context (please complete the following information):**
 - OS: fedora
 - Browser: firefox
 - Commit Hash from status endpoint:
 "commit": "9e5745b188ba6c802277de91eae0bf3ca95d893e",

**Additional context**
After re-deploying environment with correct mail-gun credentials customer adding works as expected.

**Comment by chambridge** [comment]
@lcouzens @LandoCalrizzian 
This is a valid bug, but with the 3scale branch that is about to be merged the flow for creating a customer is altered and we no longer have the on boarding flow that triggers an email generation (all that code is removed). Due to these changes I suggest we just close this out once that branch is merged to master.

**Comment by lcouzens** [comment]
Sure, sounds good to me.
