### ISSUE TITLE
Volume charges not being added to overall openshift charges

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#706]
**Describe the bug**
Volume charges not being added to overall openshift charges

**To Reproduce**
1. Add OCP provider
2. Add up totals from compute, memory, volumes endpoints
3. Compare with overall total on openshift/charges/ endpoint

**Expected behavior**
Overall openshift charge should give you the running cost for all items.

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Commit Hash from status endpoint: 712deec86544bebd5eb2f162d01d11fea5a0614e

**Additional context**
compute
```
             },
                            "derived_cost": {
                                "value": 9.6,
                                "units": "USD"
                            },
                            "cost": {
                                "value": 9.6,
                                "units": "USD"
```
memory
```
                            "derived_cost": {
                                "value": 0.96,
                                "units": "USD"
                            },
                            "cost": {
                                "value": 0.96,
                                "units": "USD"
```
volumes
```
      "derived_cost": {
                                "value": 1.86,
                                "units": "USD"
                            },
                            "cost": {
                                "value": 1.86,
                                "units": "USD"
```
Charges
```
          "derived_cost": {
                                "value": 10.56,
                                "units": "USD"
                            },
                            "cost": {
                                "value": 10.56,
                                "units": "USD"
```

**Comment by dccurtis** [comment]
`/openshift/charges` endpoint is missing the data from column `persistentvolumeclaim_charge_gb_month` in table `reporting_ocpstoragelineitem_daily_summary`.

It is currently getting the following data sources to sum the charges from the `reporting_ocpusagelineitem_daily_summary` table

```
            'report_type': {
                'charge': {
                    'aggregates': {
                        'infrastructure_cost': Sum(Value(0, output_field=DecimalField())),
                        'derived_cost': Sum(F('pod_charge_cpu_core_hours') + F('pod_charge_memory_gigabyte_hours')),
                        'cost': Sum(F('pod_charge_cpu_core_hours') + F('pod_charge_memory_gigabyte_hours')),
                    },
```

One implementation challenge is that our query handler `execute_query` is assuming it's always queuing a single database table.  Some options I was thinking about while investigating this:
1. Change the `execute_query` logic and provider mapper to allow for querying multiple tables and collapse the results.
2. Do multiple queries in the view and merge the results.
3.  Make sql changes such that the `reporting_ocpusagelineitem_daily_summary` has a column that's a view for `persistentvolumeclaim_charge_gb_month` in the `reporting_ocpstoragelineitem_daily_summary` table.  Both tables are sharing a reporting_period and report foreign keys and are both daily summarized so they should line up well.

Un-assigning since its a little larger then I initially thought to do in the current sprint.
