### ISSUE TITLE
OCP on Aws: Cannot group by tag

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#773]
**Describe the bug**
When attempting OCP on AWS is groupped by tag, the API returns a "400 Bad Request". The specific message is "Unsupported parameter" message.

/reports/openshift/infrastructures/aws/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[tag:app]=*&order_by[cost]=desc

**To Reproduce**
1. Go to 'OpenShift on Aws'
2. Group by 'Tag: app'
3. See error

**Expected behavior**
This should mimic the behavior for OCP. For example, this works for OCP:

/reports/openshift/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[tag:app]=*&order_by[cost]=desc

**Screenshots**
<img width="1184" alt="Screen Shot 2019-03-28 at 1 29 25 PM" src="https://user-images.githubusercontent.com/17481322/55179573-23265080-515e-11e9-9742-8649db633f04.png">

**Comment by lcouzens** [comment]
I was just writing some automation around this and had the exact same question/issue. @chambridge Should we be able to group_by tags with OCP on AWS endpoints? Presumably we would also be able to group on AWS and OCP tags to right?

**Comment by adberglund** [comment]
@dlabrecq @lcouzens Currently the OCP on AWS endpoints allow tag filter/grouping on AWS tags only since we are operating on AWS data. In the example above tag:app is an OCP tag and not valid. We could do some merging of tags between AWS and OCP on these endpoints but because tags are key:value pairs that can come with issues. If a row of data has a tag with the same name in OpenShift and in AWS then we either have to pick a single value for the key or double count data. How do we decide if OpenShift or the cloud provider key:value is more important when doing that merge? If we do decide to merge then we also might lose information if the value that lost is no longer represented. The other alternative would be to explicitly specify if the tag being filtered/grouped is from OpenShift or from AWS and that would end up with something _like_ `tag:OCP:app` (not necessarily exactly that, but some way to differentiate)

**Comment by chambridge** [comment]
@dlabrecq  You should be using the AWS tags.

The OCP on AWS is just a filtered view of AWS data. We are still looking at the same cost and usage report information as on the AWS details page, we have just been able to associate it with OpenShift through either Operator Metering data or the customer use of special AWS tags `openshift_project`, `openshift_node`, `openshift_cluster`.

https://koku.readthedocs.io/en/latest/providers.html#running-openshift-on-aws

If we want to change that, its a post-summit kinda thing. But I think based on the RedHat IT conversations they are essentially mirroring tags into AWS for what they actually care about so AWS has the essential tags for customers.

**Comment by dlabrecq** [comment]
Ok, I'm currently using the API below to show the tags. Sounds like an easy fix on my end. Thanks!

/tags/openshift/?filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&key_only=true
