### ISSUE TITLE
Apply pricing rates to multiple clusters

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#799]
## User Story
As a koku user, 
I want to specify which OpenShift clusters my price list applies to,
so that I can manage one price list for multiple OpenShift clusters.

See also: https://docs.google.com/document/d/1N06BRnzdAM5gTI62I43t3b8o3DgV-lBw9R7rVV4MZXQ/edit?usp=sharing

## Impacts
- API
- UI
- Docs

## Role
Koku User

## Assumptions
- API stores a list of objects that can be associated with a set of Rates
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## UI Details
The UI should allow the user to associate a Price List with a set of objects (probably tags).

## Acceptance Criteria

- [ ] Koku stores an association between Rates and other objects (e.g. tags, clusters, etc.).
- [ ] The relationship between Rates and other objects is 1-to-M. (One price list can apply to many other things.)
- [ ] The prices defined by the Rates are applied to all objects associated with that price list

**Comment by chambridge** [comment]
remove the provider_uuid from rates model:
https://github.com/project-koku/koku/blob/master/koku/rates/models.py#L47

Add foreign key from rates to provider (e.g.):
https://github.com/project-koku/koku/blob/master/koku/api/provider/models.py#L80

Need to be able to see if we can foreign key to another schema since providers are in public schema and rates is in tenant schema.

_Nice to have:_
Migrate data if possible (time box to 1 day; otherwise we will blow away rates and recreate).

Need to support PUT (update) on provider.

investigate cost/benefit of moving provider to tenant schema or rates to public (preferred in provider in tenant). What are the impacts.
^prototype the above.

Rates API should take/show a list of providers (the list can be empty).

**Comment by lcouzens** [comment]
Verified
Commit: d4de1a9035d4005a307d7116578f40b26f4d34f7
