### ISSUE TITLE
OCP on AWS: group_by tag not working

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#840]
### Proposed Solution
Create a filtered API endpoint for AWS tags that returns just the AWS tags for OCP on AWS. 
A possible implementation could be to use the `/infrastructures/aws/` path akin to our reporting APIs, and this could give the the appropriate AWS tags, but would have to live on the `/tags/openshift/` path in order to match. That might be confusing, but it could set us up for other providers on AWS. Alternatively we could just have a filter on the `/tags/aws/` endpoint that just pulls openshift matched tags. 

**Describe the bug**
Cannot group_by tag keys with the `/api/cost-management/v1/reports/openshift/infrastructures/aws/costs` API. No value is returned, which results in an empty table.

The group_by tag key still works for OCP details and AWS details.

**To Reproduce**
1. In the Koku UI, go to 'OpenShift on AWS'
2. Click on 'Group cost by'
3. Select 'TagKey: 5dc_key' or any tag key

**Expected behavior**
Not sure when this stopped working, but we're still able to obtain a list of tag keys. The user should be able to group_by the list of tags obtained.

**Screenshots**
![Screen Shot 2019-04-29 at 2 11 40 PM](https://user-images.githubusercontent.com/17481322/56917379-57589e00-6a89-11e9-8ae3-91788a8b83df.png)

Full API used:
/api/cost-management/v1/reports/openshift/infrastructures/aws/costs/?delta=cost&filter%5Blimit%5D=10&filter%5Boffset%5D=0&filter%5Bresolution%5D=monthly&filter%5Btime_scope_units%5D=month&filter%5Btime_scope_value%5D=-1&group_by%5Btag%3A5dc_key%5D=%2A&order_by%5Bcost%5D=desc

**Comment by chambridge** [comment]
So the issue here is not quite correct. There are tag keys that work; for example `openshift_project`.

![image.png](https://images.zenhubusercontent.com/59651c6861b4ca3b0a740ad4/95a6636b-97ef-4bba-a85e-01e4e9b0d4ac)

Currently, we use the AWS tag list and in this view. What is being seen is that all AWS tags don't necessarily map to an OpenShift resource; so in some cases the group_by returns an empty set.

It would be nice if we could return just the subset of AWS tags that have OpenShift related uses.

**Comment by adberglund** [comment]
`/api/v1/tags/openshift/infrastructures/aws/` would return AWS tags that are OCP matched.
