### ISSUE TITLE
AWS costs for instance/storage/network/database don't add up to the overall total

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#849]
**Describe the bug**
Sum of totals for instance/storage/network/database reports don't add up to the overall cost report total.

**To Reproduce**
1. GET the respectable reports 
2. Summarize the individual values
3. See that the values don't add up to the overall total

**Expected behavior**
Correct values returned

**Screenshots**
Screenshot from the UI: 
![Screenshot from 2019-05-03 14-06-56](https://user-images.githubusercontent.com/46324552/57137581-9439d300-6db0-11e9-8a82-6519823dd42b.png)

**Context (please complete the following information):**
 - OS: RHEL
 - Browser: Chrome 73
 - Commit Hash from status endpoint: e7af87994e89a255b925e2eee0cb6f9e01ff6703

**Additional context**
We can see this issue both on CI and PROD

**Comment by adberglund** [comment]
@dchorvat1 @lcouzens As it stands, this is the expected behavior. The cards for specific cost (database, storage, network, and compute) are just a subset of the total cost. There could be lots of AWS services that are not included in those cards. Just as an example any compute costs that aren't EC2 (say they're using EKS or Lambda) would not be included in the compute card as it exists today. To make matters worse the compute, database, and network cards are based on specific services in AWS. The storage card groups together any cost that has a "product family" of storage. That means that it can include some of the EC2 storage cost that was already counted in the Compute (EC2) card. I think there's some discussions we should have with product around that and whether we're okay with this, or want consistency between the cards.
