### ISSUE TITLE
OpenShift data should always be bigger or equal than OpenShift on Cloud data

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#915]
**Describe the bug**
The numbers for OpenShift on Cloud should be always lower than the numbers of OpenShift, as the latter is calculated as the sum of the costs in AWS and the costs calculated by the price list.

**To Reproduce**
Go to the tabs for OpenShift on Cloud and OPenShift, the numbers should be equal as the price list is empty

**Expected behavior**
They should be the same number

**Screenshots**
If applicable, add screenshots to help explain your problem. First Openshift, second openshift on cloud.

![Cost_Management_1](https://user-images.githubusercontent.com/7500590/60270929-6314e500-98bf-11e9-85d5-f1861f26bc42.png)
![Cost_Management_2](https://user-images.githubusercontent.com/7500590/60270939-6a3bf300-98bf-11e9-864f-b415cba4ef2d.png)

**Context (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Commit Hash from status endpoint:

**Additional context**

**Comment by lcouzens** [comment]
Looking at the API endpoints it looks like we are only showing infrastructure costs on both OCP and OCP on AWS endpoints but the values are different.

The ocp endpoint should have `derived_cost` and `infra_cost`

api/cost-management/v1/reports/openshift/infrastructures/aws/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily&group_by[cluster]=*
```{
    "meta": {
        "count": 27,
        "filter": {
            "resolution": "daily",
            "time_scope_value": "-1",
            "time_scope_units": "month"
        },
        "group_by": {
            "cluster": [
                "*"
            ]
        },
        "total": {
            "infrastructure_cost": {
                "value": 413.164092632,
                "units": "USD"
            },
            "derived_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "cost": {
                "value": 413.164092632,
                "units": "USD"
            }
        }
    },```

api/cost-management/v1/reports/openshift/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily&group_by[cluster]=*
```{
    "meta": {
        "count": 27,
        "filter": {
            "resolution": "daily",
            "time_scope_value": "-1",
            "time_scope_units": "month"
        },
        "group_by": {
            "cluster": [
                "*"
            ]
        },
        "total": {
            "infrastructure_cost": {
                "value": 176.382557,
                "units": "USD"
            },
            "derived_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "cost": {
                "value": 176.382557,
                "units": "USD"
            }
        }
    },```

Also this is seen on PROD using the demo account

**Comment by lcouzens** [comment]
I investigated this a little more and things look a little different, from the data I ingested it looks like the openshift endpoint is not getting the infrastructure_cost populated correctly.

openshift endpoint
```{
    "meta": {
        "count": 10,
        "filter": {
            "time_scope_value": "-10",
            "time_scope_units": "day",
            "resolution": "daily"
        },
        "total": {
            "infrastructure_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "derived_cost": {
                "value": 15.215,
                "units": "USD"
            },
            "cost": {
                "value": 15.215,
                "units": "USD"
            }
        }
    },```

openshift on aws endpoint
```

{
    "meta": {
        "count": 3,
        "filter": {
            "resolution": "daily",
            "time_scope_value": "-1",
            "time_scope_units": "month"
        },
        "group_by": {
            "cluster": [
                "*"
            ]
        },
        "total": {
            "infrastructure_cost": {
                "value": 252.0,
                "units": "USD"
            },
            "derived_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "cost": {
                "value": 252.0,
                "units": "USD"
            }
        }
    },```

On the plus side I was able to reproduce the same results locally this time. My guess is there is some table summary issue on the aws side.

**Comment by lcouzens** [comment]
OK I think I know what the issue is @adberglund its the problem we saw before when you add the OCP source prior to adding the AWS source. In my automation I was doing a table_update to fix things I think but we really need to be able to add these in any order. Maybe you can confirm what I am thinking. Certainly looks to be this when testing locally.

**Comment by dccurtis** [comment]
Current Findings

1.  Ingesting OCP then AWS results in no updates to `reports/openshift/costs/`
2. Ingesting AWS then OCP updates `reports/openshift/costs/` as expected.
3. Once OCP is ingested, the problem corrects itself, but could potentially occur again once AWS data comes in.
4. Re-summarizing the with the Masu /report_data admin endpoint temporarily corrects the problem (until AWS is ingested next)

Root Cause:
`OCPCloudReportSummaryUpdater` is ran after both AWS and OCP summarization sessions.  The method `populate_cost_summary_table` updates the database table `reporting_ocpcosts_summary`.  Which is where the data for `reports/openshift/costs/` comes from.  This summary step is only done when the OCP cluster-id is known which means its only done when the OCP report summary is ran.

The changes made https://github.com/project-koku/masu/pull/452 made it so report summary is only attempted if there is new line item data to summarize.  For this case there is no new OCP data to summarize so `OCPCloudReportSummaryUpdater` never runs.  OCP costs summary table is only being updated after new OCP data is ingested.

I was able to temporarily fix this problem by unconditionally adding reports to summarize in `get_report_files` even if no new data was detected.  This would be more inline with the old flow where we would unconditionally summarize.

Idea to fix this:
* Enhance masu to be able to detect provider dependencies (*This* OCP is running on *this* AWS).  Run `OCPCloudReportSummaryUpdater` whenever either provider in the OCP-on-AWS relationship changes.  Note: This would be simpler if the OCP on AWS relationship was user specified rather then us detecting it.

**Comment by dccurtis** [comment]
While testing the problem described yesterday I found another problem that could be contributing to this.  I'm seeing duplicate OCP-on-AWS entries being added `reporting_ocpawscostlineitem_daily_summary` whenever a second (not on AWS) OCP cluster ingests data.  Most likely we are missing a group_by cluster_id in the raw SQL.  Investigating that next. 

Full reproduction steps and example is included in the attached file:
[issue_915_investigation.txt](https://github.com/project-koku/koku/files/3374610/issue_915_investigation.txt)

**Comment by dccurtis** [comment]
The SQL problem appears to be happening when `populate_ocp_on_aws_cost_daily_summary` is passed `cluster_id=None`.  In this case there is no ocp_where_clause appended to the raw SQL query so the `reporting_ocpawscostlineitem_daily_summary.sql` file is incorrectly including results because the other `WHERE` parameters (i.e. usage_start, usage_end) match but the constraint for a cluster-id is not included.

**Comment by lcouzens** [comment]
Verified 
Commit: ce0ff541b08bfd83acaa25cdb6e987cc29294d1c
