### ISSUE TITLE
Unsupported AWS Tag-Mo units

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#916]
The AWS 'Storage services' card is showing units as 'Tag-Mo', instead of the expected 'GB-Mo'.

Updated screenshot:
<img width="425" alt="Screen Shot 2019-08-08 at 11 29 07 AM" src="https://user-images.githubusercontent.com/17481322/62716223-ccfcd000-b9cf-11e9-807a-a8672448d142.png">

Apparently, AWS has a new `User-Defined Cost Allocation Tags` feature.
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/custom-tags.html

We will update the UI to ensure unknown types don't break translations. However, koklu may need to handle calculations differently? We probably don't want to mix units in the same cards/charts?

The request is:
https://cloud.redhat.com/api/cost-management/v1/reports/aws/storage/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[limit]=3&group_by[account]=*

The request result:
```
{
  "meta": {
    "count": 1,
    "filter": {
      "resolution": "monthly",
      "time_scope_value": "-1",
      "time_scope_units": "month",
      "limit": 3
    },
    "group_by": {
      "account": [
        "*"
      ]
    },
    "total": {
      "infrastructure_cost": {
        "value": 6.416944781,
        "units": "USD"
      },
      "derived_cost": {
        "value": 0,
        "units": "USD"
      },
      "cost": {
        "value": 6.416944781,
        "units": "USD"
      },
      "usage": {
        "value": 112.830580872,
        "units": "GB-Mo"
      }
    }
  },
  "links": {
    "first": "/api/cost-management/v1/reports/aws/storage/?filter%5Blimit%5D=3&filter%5Bresolution%5D=monthly&filter%5Btime_scope_units%5D=month&filter%5Btime_scope_value%5D=-1&group_by%5Baccount%5D=%2A&limit=100&offset=0",
    "next": null,
    "previous": null,
    "last": "/api/cost-management/v1/reports/aws/storage/?filter%5Blimit%5D=3&filter%5Bresolution%5D=monthly&filter%5Btime_scope_units%5D=month&filter%5Btime_scope_value%5D=-1&group_by%5Baccount%5D=%2A&limit=100&offset=0"
  },
  "data": [
    {
      "date": "2019-06",
      "accounts": [
        {
          "account": "256293412812",
          "values": [
            {
              "date": "2019-06",
              "account": "256293412812",
              "infrastructure_cost": {
                "value": 6.416944781,
                "units": "USD"
              },
              "derived_cost": {
                "value": 0,
                "units": "USD"
              },
              "cost": {
                "value": 6.416944781,
                "units": "USD"
              },
              "usage": {
                "value": 112.830580872,
                "units": "Tag-Mo"
              },
              "account_alias": "256293412812"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by adberglund** [comment]
We should look at the cost and usage report to look for "gorp" (Chris' word) (that is whether we get 2 lines, one for the billed unit, and one for the tag unit) and see if we can just display the unit we were previously expecting. This would get us back to where we were as we determine how to handle tag-units. We can break this into appropriate sub-issues once we have confirmed what the data looks like.

**Comment by blentz** [comment]
See here: https://docs.aws.amazon.com/AmazonS3/latest/dev/aws-usage-report-understand.html

![screenshot.png](https://images.zenhubusercontent.com/5ab00ec24b5806bc2bcb7db2/4e0b7fae-6b98-4f25-9a32-79c034744c02)

**Comment by chambridge** [comment]
So the `api/cost-management/v1/reports/aws/storage/` API is doing a query on AWS data filtered by product_family that contains "Storage":
https://github.com/project-koku/koku/blob/master/koku/api/report/queries.py#L193

This product family can have multiple units that appear now. I can now see both `GB-Mo` and `Tag-Mo` based on our internal demo data.

If we changed the code here:
https://github.com/project-koku/koku/blob/master/koku/api/report/aws/aws_query_handler.py#L75
https://github.com/project-koku/koku/blob/master/koku/api/report/aws/aws_query_handler.py#L111

To use Max() which would give us `GB-Mo` because of alphabetical ordering, but this would somewhat mask that some of the data could be coming from `Tag-Mo`.

**Comment by chambridge** [comment]
If we also wanted to only show `GB-Mo` data we could potentially add complexity to the following line of code:
https://github.com/project-koku/koku/blob/master/koku/api/report/queries.py#L1046
Instead of assuming a single directory filter it could be an array of filter dictionaries that get added. We could add something like:
```
	'filter': [{
		'field': 'product_family',
		'operation': 'contains',
		'parameter': 'Storage'
	}, {
		'field': 'unit',
		'operation': 'exact',
		'parameter': 'GB-Mo'
	}]
```

Less in favor of adding more complexity here but it would force this cost back to a single unit.

**Comment by adberglund** [comment]
We will need to filter out entries that are not `GB-Mo`

**Comment by lcouzens** [comment]
Verified
Commit "d5d24666043e6e6bdb6964ac7e093f523f9a6b86"
